example/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),    
]

listings/urls.py
from django.urls import path
from .import views


app_name = 'listings'

urlpatterns = [
    # Homepage
    path('', views.index, name='index'),
    # Listings Page
    path('all_listings/', views.all_listings, name='all_listings'),
    # New Listing
    path('new_listing/', views.new_listing, name='new_listing'),
   
]

listings/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime


class Listings(models.Model):

    class SaleType(models.TextChoices):
        PICK_UP = "Available for pickup"
        SHIP = "Available for shipping"

    class ConditionType(models.TextChoices):
        USED = "Used"
        NEW = "New"

    class ProductType(models.TextChoices):
        BIKE = "Bike"
        PARTS = "Parts"
        MODELS = "Models"
        OTHER = "Other"

  
    title = models.CharField(max_length=100)
    condition = models.CharField(
        max_length=50, choices=ConditionType.choices, default=ConditionType.USED)
    product_type = models.CharField(
        max_length=50, choices=ProductType.choices, default=ProductType.BIKE)
    sale_type = models.CharField(
        max_length=50, choices=SaleType.choices, default=SaleType.SHIP)
    price = models.FloatField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    zipcode = models.CharField(max_length=25)
    main_photo = models.ImageField()
    photo_1 = models.ImageField()
    photo_2 = models.ImageField(blank=True)
    list_date = models.DateTimeField(default=now)
    contact_email = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Listings"

listings/forms.py
from django import forms
from .models import Listings


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listings
        fields = ['title', 'condition', 'product_type', 'sale_type', 'price', 'main_photo', 'photo_1',
                  'photo_2', 'city', 'state', 'zipcode', 'contact_email', 'list_date']

listings/views.py
def new_listing(request):
    if request.method != 'POST':
        form = ListingForm()
    else:
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listings:all_listings')
      
    context = {'form': form}
    return render(request, 'listings/new_listing.html', context)

listings/templates/listings/all_listings.html
<h1>LISTINGS</h1>

<div class="col"> 
    <div class="card">
        {% for listing in all_listings %}

            <p><b>Title:</b> {{ listing.title }}</p>
            <p><b>Condition:</b> {{ listing.condition }}</p>
            <p><b>Sale Type:</b> {{ listing.sale_type }}</p> 
            <p><b>Price:</b> $ {{ listing.price|floatformat:2 }}</p>
            <p><b>Location:</b> {{ listing.city }}, {{ listing.state }}</p> 
            <p><b>Post Date:</b> {{ listing.list_date }}</p> 
            <ul>
                <a class="btn" href="">View Listing</a>
            </ul>
            <hr/>
        {% empty %}
            <h3>No listings found. Try again.</h3>
        {% endfor %} 
    </div>
</div>

listings/templates/listings/index.html
<h3>Bike Find3r</h3>

<p>This is a homepage</p>

listings/templates/listings/new_listing.html
<h1>NEW LISTING</h1>

<form action="{% url 'listings:new_listing' %}" method='post' enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <button type="submit" class="btn">Create Listing</button>
</form>